# default server port. kept variable name as PORT as heroku by default provides this variable with random values
server:
  port: ${PORT:0}

# default active profile
spring:
  profiles:
    active:
    - dev 

# default service discovery
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    enabled: ${REGISTER_TO_EUREKA:true}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
 
#refresh client config at runtime and interval in seconds. custom property
client:
  config:
    auto-refresh:
      enabled: false
      delay: 30
